# Generated by Django 2.1.15 on 2020-05-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
